import { useState } from 'react'
import { MINES, SUBSIDIARIES, REPORT_TYPES } from '../data/stubs.js'

const STUB_EXTRACTED = {
  'Total Proven Reserves':      '18.7 billion tonnes',
  'Current Production Rate':    '142.6 MT / quarter',
  'Average Seam Thickness':     '3.4 m',
  'Average Ash Content':        '24.3%',
  'OBR Ratio (opencast)':       '3.8 : 1',
  'Active Mine Galleries':      '214',
  'LTIFR (Safety Metric)':      '0.23 per lakh man-shifts',
  'Env. Clearance Validity':    'Valid until FY 2026-27',
  'Methane Drainage Capacity':  '12,400 m³/day',
  'Reserves Life Index':        '~82 years at current production rate',
}

export default function ReportGenerator() {
  const [title,        setTitle]        = useState('Geological & Production Summary Report')
  const [reportType,   setReportType]   = useState(REPORT_TYPES[0])
  const [subsidiary,   setSubsidiary]   = useState('Eastern Coalfields Ltd (ECL)')
  const [mine,         setMine]         = useState(MINES[0])
  const [periodFrom,   setPeriodFrom]   = useState('2024-01-01')
  const [periodTo,     setPeriodTo]     = useState('2024-03-31')
  const [preparedBy,   setPreparedBy]   = useState('CMPDI Technical Division')
  const [approvedBy,   setApprovedBy]   = useState('General Manager, Mining')
  const [refNo,        setRefNo]        = useState('')
  const [notes,        setNotes]        = useState('')
  const [outputFmt,    setOutputFmt]    = useState('.docx (Word)')
  const [inclToc,      setInclToc]      = useState(true)
  const [inclTrail,    setInclTrail]    = useState(true)

  // Sections
  const [sReserves,   setSReserves]   = useState(true)
  const [sProduction, setSProduction] = useState(true)
  const [sGeology,    setSGeology]    = useState(true)
  const [sEnv,        setSEnv]        = useState(true)
  const [sSafety,     setSSafety]     = useState(true)
  const [sForecast,   setSForecast]   = useState(false)
  const [sBorehole,   setSBorehole]   = useState(false)
  const [sHistorical, setSHistorical] = useState(false)

  // Sources
  const [srcPdf,     setSrcPdf]     = useState(true)
  const [srcExcel,   setSrcExcel]   = useState(true)
  const [srcImages,  setSrcImages]  = useState(false)
  const [srcArchive, setSrcArchive] = useState(false)
  const [srcLive,    setSrcLive]    = useState(false)

  const [generating, setGenerating] = useState(false)
  const [done,       setDone]       = useState(false)
  const [copied,     setCopied]     = useState(false)

  const autoRef = refNo || `CMPDI/GEO/${new Date().getFullYear()}/Q${Math.ceil((new Date().getMonth() + 1) / 3)}/001`

  const handleGenerate = e => {
    e.preventDefault()
    setGenerating(true); setDone(false)
    setTimeout(() => { setGenerating(false); setDone(true) }, 1800)
  }

  const selectedSections = [
    sReserves   && 'Reserve Estimates',
    sProduction && 'Production Statistics',
    sGeology    && 'Geological Profile',
    sEnv        && 'Environmental Metrics',
    sSafety     && 'Safety Statistics (DGMS)',
    sForecast   && 'Production Forecast',
    sBorehole   && 'Borehole / Seam Data',
    sHistorical && 'Historical Comparison',
  ].filter(Boolean)

  const buildReportText = () => {
    const sep = '='.repeat(60)
    const lines = [
      sep,
      'CMPDI / Coal India Limited',
      title.toUpperCase(),
      sep,
      '',
      `Reference No : ${autoRef}`,
      `Report Type  : ${reportType}`,
      `Subsidiary   : ${subsidiary}`,
      `Mine         : ${mine}`,
      `Period       : ${periodFrom} to ${periodTo}`,
      `Prepared By  : ${preparedBy}`,
      `Approved By  : ${approvedBy}`,
      `Generated On : ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}`,
      '',
      sep,
      'SECTIONS INCLUDED',
      sep,
      ...selectedSections.map((s, i) => `  ${i + 1}. ${s}`),
      '',
      sep,
      'AUTO-EXTRACTED DATA POINTS',
      sep,
      ...Object.entries(STUB_EXTRACTED).map(([k, v]) => `  ${k.padEnd(30)} : ${v}`),
    ]

    if (notes) {
      lines.push('', sep, 'REMARKS / EXECUTIVE SUMMARY', sep, notes)
    }

    if (inclTrail) {
      const sources = [
        srcPdf     && 'Geological Survey PDFs',
        srcExcel   && 'Production Excel/CSV',
        srcImages  && 'Geological Maps',
        srcArchive && 'Historical Archives',
        srcLive    && 'Live Portal/API',
      ].filter(Boolean).join(', ')
      lines.push(
        '', sep,
        'DATA TRACEABILITY APPENDIX',
        sep,
        `  Sources: ${sources}`,
        '  Generated by PRAGYA MineInsight AI',
        '  Smart India Hackathon 2024 · Ministry of Coal',
      )
    }

    lines.push('', sep)
    return lines.join('\n')
  }

  const handleDownloadDocx = () => {
    const content = buildReportText()
    const blob = new Blob([content], { type: 'application/msword' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `${title.replace(/\s+/g, '_')}.doc`
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleDownloadPdf = () => {
    const content = buildReportText()
    const printWin = window.open('', '_blank')
    printWin.document.write(`
      <html>
        <head>
          <title>${title}</title>
          <style>
            body { font-family: 'Courier New', monospace; font-size: 12px; padding: 40px; white-space: pre-wrap; }
            @media print { body { padding: 20px; } }
          </style>
        </head>
        <body>${content.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</body>
      </html>
    `)
    printWin.document.close()
    printWin.focus()
    setTimeout(() => { printWin.print(); printWin.close() }, 300)
  }

  const handleCopyRef = () => {
    navigator.clipboard.writeText(autoRef).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  return (
    <div>
      <div className="page-title">Automated Report Generation Platform</div>
      <div className="page-subtitle">
        Generate structured, data-backed reports in .docx or .pdf format.
        Supports geological summaries, production reports, parliamentary responses,
        environmental compliance, and safety reports for all eight CIL subsidiaries.
        Every report includes a data traceability appendix.
      </div>

      <form onSubmit={handleGenerate}>
        {/* Section 1 — Report Identity */}
        <div className="form-section">
          <div className="form-section-title">1. Report Identity</div>
          <div className="form-row">
            <div className="form-group">
              <label className="form-label">Report Title</label>
              <input className="form-input" value={title} onChange={e => setTitle(e.target.value)} required />
            </div>
            <div className="form-group">
              <label className="form-label">Report Type</label>
              <select className="form-select" value={reportType} onChange={e => setReportType(e.target.value)}>
                {REPORT_TYPES.map(r => <option key={r}>{r}</option>)}
              </select>
            </div>
          </div>
          <div className="form-row">
            <div className="form-group">
              <label className="form-label">CIL Subsidiary</label>
              <select className="form-select" value={subsidiary} onChange={e => setSubsidiary(e.target.value)}>
                {SUBSIDIARIES.filter(s => s.code !== 'ALL').map(s =>
                  <option key={s.code}>{s.name}</option>)}
              </select>
            </div>
            <div className="form-group">
              <label className="form-label">Mine / Coalfield</label>
              <select className="form-select" value={mine} onChange={e => setMine(e.target.value)}>
                {MINES.map(m => <option key={m}>{m}</option>)}
              </select>
            </div>
          </div>
        </div>

        {/* Section 2 — Period & Authorship */}
        <div className="form-section">
          <div className="form-section-title">2. Reporting Period &amp; Authorship</div>
          <div className="form-row-4">
            <div className="form-group">
              <label className="form-label">Period From</label>
              <input className="form-input" type="date" value={periodFrom}
                onChange={e => setPeriodFrom(e.target.value)} />
            </div>
            <div className="form-group">
              <label className="form-label">Period To</label>
              <input className="form-input" type="date" value={periodTo}
                onChange={e => setPeriodTo(e.target.value)} />
            </div>
            <div className="form-group">
              <label className="form-label">Prepared By</label>
              <input className="form-input" value={preparedBy}
                onChange={e => setPreparedBy(e.target.value)} />
            </div>
            <div className="form-group">
              <label className="form-label">Approved / Reviewing Officer</label>
              <input className="form-input" value={approvedBy}
                onChange={e => setApprovedBy(e.target.value)} />
            </div>
          </div>
          <div className="form-group" style={{ maxWidth: 360 }}>
            <label className="form-label">Reference / File Number</label>
            <input className="form-input" placeholder="e.g. CMPDI/GEO/2024/Q3/001"
              value={refNo} onChange={e => setRefNo(e.target.value)} />
          </div>
        </div>

        {/* Section 3 — Data Sections */}
        <div className="form-section">
          <div className="form-section-title">3. Data Sections to Include</div>
          <div className="grid-4">
            {[
              [sReserves,   setSReserves,   'Reserve Estimates'],
              [sProduction, setSProduction, 'Production Statistics'],
              [sGeology,    setSGeology,    'Geological Profile'],
              [sEnv,        setSEnv,        'Environmental Metrics'],
              [sSafety,     setSSafety,     'Safety Statistics (DGMS)'],
              [sForecast,   setSForecast,   'Production Forecast'],
              [sBorehole,   setSBorehole,   'Borehole / Seam Data'],
              [sHistorical, setSHistorical, 'Historical Comparison'],
            ].map(([val, setter, label]) => (
              <div key={label} className="checkbox-group">
                <input type="checkbox" id={label} checked={val}
                  onChange={e => setter(e.target.checked)} />
                <label htmlFor={label}>{label}</label>
              </div>
            ))}
          </div>
        </div>

        {/* Section 4 — Data Sources */}
        <div className="form-section">
          <div className="form-section-title">4. Data Sources to Reference</div>
          <div className="grid-4">
            {[
              [srcPdf,     setSrcPdf,     'Geological Survey PDFs'],
              [srcExcel,   setSrcExcel,   'Production Excel / CSV'],
              [srcImages,  setSrcImages,  'Geological Maps / Images'],
              [srcArchive, setSrcArchive, 'Historical Archives'],
              [srcLive,    setSrcLive,    'Live Portal / API Data'],
            ].map(([val, setter, label]) => (
              <div key={label} className="checkbox-group">
                <input type="checkbox" id={`src-${label}`} checked={val}
                  onChange={e => setter(e.target.checked)} />
                <label htmlFor={`src-${label}`}>{label}</label>
              </div>
            ))}
          </div>
        </div>

        {/* Section 5 — Output & Notes */}
        <div className="form-section">
          <div className="form-section-title">5. Output Format &amp; Notes</div>
          <div className="form-row">
            <div>
              <div className="form-group">
                <label className="form-label">Output Format</label>
                <select className="form-select" value={outputFmt} onChange={e => setOutputFmt(e.target.value)}>
                  <option>.docx (Word)</option>
                  <option>.pdf (via conversion)</option>
                  <option>Both .docx and .pdf</option>
                </select>
              </div>
              <div className="checkbox-group" style={{ marginBottom: 6 }}>
                <input type="checkbox" id="incl-toc" checked={inclToc}
                  onChange={e => setInclToc(e.target.checked)} />
                <label htmlFor="incl-toc">Include Table of Contents</label>
              </div>
              <div className="checkbox-group">
                <input type="checkbox" id="incl-trail" checked={inclTrail}
                  onChange={e => setInclTrail(e.target.checked)} />
                <label htmlFor="incl-trail">Include Data Traceability Appendix</label>
              </div>
            </div>
            <div className="form-group">
              <label className="form-label">Remarks / Executive Summary (optional)</label>
              <textarea className="form-textarea" style={{ minHeight: 100 }}
                placeholder="Add context for the reviewing officer…"
                value={notes} onChange={e => setNotes(e.target.value)} />
            </div>
          </div>
        </div>

        <button className="btn btn-primary" type="submit" disabled={generating}>
          {generating ? '⟳ Generating report…' : '⊟ Generate Report'}
        </button>
      </form>

      {generating && (
        <div style={{ marginTop: 14 }}>
          <div className="progress-bar-wrap">
            <div className="progress-bar-fill" style={{ width: '70%' }} />
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 5 }}>
            Extracting data fields and rendering Jinja2 template…
          </div>
        </div>
      )}

      {done && (
        <>
          <div className="alert alert-success" style={{ marginTop: 16 }}>
            <span>✓</span>
            Report generated successfully. Preview below; download when ready.
          </div>

          <div className="grid-2" style={{ marginTop: 16 }}>
            <div className="card">
              <div className="card-title">Report Parameters</div>
              <table>
                <tbody>
                  {[
                    ['Title',        title],
                    ['Type',         reportType],
                    ['Subsidiary',   subsidiary],
                    ['Mine',         mine],
                    ['Period',       `${periodFrom} → ${periodTo}`],
                    ['Prepared By',  preparedBy],
                    ['Approved By',  approvedBy],
                    ['Reference',    autoRef],
                    ['Sections',     selectedSections.join(', ')],
                    ['Format',       outputFmt],
                    ['Traceability', inclTrail ? 'Yes — appendix included' : 'No'],
                  ].map(([k, v]) => (
                    <tr key={k}>
                      <td style={{ fontWeight: 600, width: '38%', fontSize: '0.75rem',
                        color: 'var(--primary)', paddingRight: 12 }}>{k}</td>
                      <td style={{ fontSize: '0.78rem' }}>{v}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="card">
              <div className="card-title">Auto-Extracted Data Points</div>
              <table>
                <tbody>
                  {Object.entries(STUB_EXTRACTED).map(([k, v]) => (
                    <tr key={k}>
                      <td style={{ fontWeight: 600, fontSize: '0.75rem',
                        color: 'var(--primary)', paddingRight: 12, width: '55%' }}>{k}</td>
                      <td style={{ fontSize: '0.78rem', color: 'var(--text-body)' }}>{v}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <div className="btn-group" style={{ marginTop: 16 }}>
            <button className="btn btn-primary" onClick={handleDownloadDocx}>⬇ Download .docx</button>
            <button className="btn btn-outline" onClick={handleDownloadPdf}>⬇ Download .pdf</button>
            <button className="btn btn-outline">✉ Send for Officer Review</button>
            <button className="btn btn-outline" onClick={handleCopyRef}>
              {copied ? '✓ Copied!' : '⊟ Copy Reference Number'}
            </button>
          </div>
        </>
      )}
    </div>
  )
}
